[versions]
compose = "1.0.0"
kotlin = "1.5.10"

[libraries]
# AndroidX libraries
androidx-compose-activity = "androidx.activity:activity-compose:1.3.0"
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

[bundles]