[versions]
accompanist = "0.22.0-rc"
coil = "2.0.0-alpha06"
compose = "1.1.0-rc01"
composeCompiler = "1.1.0-rc02"
coroutines = "1.6.0"
dagger = "2.40.5"
exoplayer = "2.16.1"
hilt = "2.40.5"
kotlin = "1.6.10"
lifecycle = "2.4.0"
okHttp = "4.9.3"
paging = "3.1.0"

[libraries]
# Android Gradle Plugin
android-pluginGradle = { module = "com.android.tools.build:gradle", version = "7.1.0-beta05" }

# AndroidX Compose libraries
androidx-compose-activity = "androidx.activity:activity-compose:1.4.0"
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-materialIcons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

# Hilt
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0-rc01" }

# Navigation
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.4.0-rc01"

# LifeCycle
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

# Paging
androidx-paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "paging" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }

# Image Loading
coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

# Dependency Injection
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
dagger-hilt-pluginGradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }

# ExoPlayer
exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }
exoplayer-extension-mediasession = { module = "com.google.android.exoplayer:extension-mediasession", version.ref = "exoplayer" }
exoplayer-extension-okHttp = { module = "com.google.android.exoplayer:extension-okhttp", version.ref = "exoplayer" }

# Google
google-accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
google-accompanist-insets-ui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
google-accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
google-accompanist-systemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

# Kotlin
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# NewPipe Extractor
newpipe-extractor = "com.github.TeamNewPipe.NewPipeExtractor:NewPipeExtractor:v0.21.12"

# OkHttp3
okHttp3-okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }

[bundles]
