[versions]
accompanist = "0.22.0-rc"
compose = "1.1.0-rc01"
composeCompiler = "1.1.0-rc02"
kotlin = "1.6.10"

[libraries]
# AndroidX Compose libraries
androidx-compose-activity = "androidx.activity:activity-compose:1.4.0"
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-materialIcons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

# Navigation
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.4.0-rc01"

# Google
google-accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
google-accompanist-systemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

[bundles]