name: Deploy beta CI

on:
  push:
    branches:
      - develop

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' && github.event.ref == 'refs/heads/develop'"
    timeout-minutes: 30
    env:
      TERM: dumb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build release apk
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-dependencies-cache-key: gradle/libs.versions.toml
          arguments: assembleRelease

      - name: Sign release apk
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Delete release tag if it exists
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release for tags
        uses: softprops/action-gh-release@v1
        with:
          name: 'Latest snapshot build'
          tag_name: 'latest'
          prerelease: true
          generate_release_notes: true
          files: ${{steps.sign_apk.outputs.signedReleaseFile}}
